/**
 * Auto-generated by scripts/download-audio.ts
 * Maps remote audio URLs to bundled require() asset IDs.
 * Do not edit manually.
 */

// Challenge audio: remote URL -> bundled asset
const CHALLENGE_AUDIO: Record<string, number> = {
  "https://assets.linguaquest.app/audio/i1-p1-q1.mp3": require("@/assets/audio/challenges/i1-p1-q1.mp3"),
  "https://assets.linguaquest.app/audio/i1-p1-q2.mp3": require("@/assets/audio/challenges/i1-p1-q2.mp3"),
  "https://assets.linguaquest.app/audio/i1-p2-q1.mp3": require("@/assets/audio/challenges/i1-p2-q1.mp3"),
  "https://assets.linguaquest.app/audio/i1-p2-q2.mp3": require("@/assets/audio/challenges/i1-p2-q2.mp3"),
  "https://assets.linguaquest.app/audio/i1-p3-q1.mp3": require("@/assets/audio/challenges/i1-p3-q1.mp3"),
  "https://assets.linguaquest.app/audio/i1-p3-q2.mp3": require("@/assets/audio/challenges/i1-p3-q2.mp3"),
  "https://assets.linguaquest.app/audio/i1-p4-q1.mp3": require("@/assets/audio/challenges/i1-p4-q1.mp3"),
  "https://assets.linguaquest.app/audio/i1-p4-q2.mp3": require("@/assets/audio/challenges/i1-p4-q2.mp3"),
  "https://assets.linguaquest.app/audio/i1-p5-q1.mp3": require("@/assets/audio/challenges/i1-p5-q1.mp3"),
  "https://assets.linguaquest.app/audio/i1-p5-q2.mp3": require("@/assets/audio/challenges/i1-p5-q2.mp3"),
  "https://assets.linguaquest.app/audio/i2-p1-q1.mp3": require("@/assets/audio/challenges/i2-p1-q1.mp3"),
  "https://assets.linguaquest.app/audio/i2-p1-q2.mp3": require("@/assets/audio/challenges/i2-p1-q2.mp3"),
  "https://assets.linguaquest.app/audio/i2-p2-q1.mp3": require("@/assets/audio/challenges/i2-p2-q1.mp3"),
  "https://assets.linguaquest.app/audio/i2-p2-q2.mp3": require("@/assets/audio/challenges/i2-p2-q2.mp3"),
  "https://assets.linguaquest.app/audio/i2-p3-q1.mp3": require("@/assets/audio/challenges/i2-p3-q1.mp3"),
  "https://assets.linguaquest.app/audio/i2-p3-q2.mp3": require("@/assets/audio/challenges/i2-p3-q2.mp3"),
  "https://assets.linguaquest.app/audio/i2-p4-q1.mp3": require("@/assets/audio/challenges/i2-p4-q1.mp3"),
  "https://assets.linguaquest.app/audio/i2-p4-q2.mp3": require("@/assets/audio/challenges/i2-p4-q2.mp3"),
  "https://assets.linguaquest.app/audio/i2-p5-q1.mp3": require("@/assets/audio/challenges/i2-p5-q1.mp3"),
  "https://assets.linguaquest.app/audio/i2-p5-q2.mp3": require("@/assets/audio/challenges/i2-p5-q2.mp3"),
  "https://assets.linguaquest.app/audio/i3-p1-q1.mp3": require("@/assets/audio/challenges/i3-p1-q1.mp3"),
  "https://assets.linguaquest.app/audio/i3-p1-q2.mp3": require("@/assets/audio/challenges/i3-p1-q2.mp3"),
  "https://assets.linguaquest.app/audio/i3-p2-q1.mp3": require("@/assets/audio/challenges/i3-p2-q1.mp3"),
  "https://assets.linguaquest.app/audio/i3-p2-q2.mp3": require("@/assets/audio/challenges/i3-p2-q2.mp3"),
  "https://assets.linguaquest.app/audio/i3-p3-q1.mp3": require("@/assets/audio/challenges/i3-p3-q1.mp3"),
  "https://assets.linguaquest.app/audio/i3-p3-q2.mp3": require("@/assets/audio/challenges/i3-p3-q2.mp3"),
  "https://assets.linguaquest.app/audio/i3-p4-q1.mp3": require("@/assets/audio/challenges/i3-p4-q1.mp3"),
  "https://assets.linguaquest.app/audio/i3-p4-q2.mp3": require("@/assets/audio/challenges/i3-p4-q2.mp3"),
  "https://assets.linguaquest.app/audio/i3-p5-q1.mp3": require("@/assets/audio/challenges/i3-p5-q1.mp3"),
  "https://assets.linguaquest.app/audio/i3-p5-q2.mp3": require("@/assets/audio/challenges/i3-p5-q2.mp3"),
  "https://assets.linguaquest.app/audio/i4-p1-q1.mp3": require("@/assets/audio/challenges/i4-p1-q1.mp3"),
  "https://assets.linguaquest.app/audio/i4-p1-q2.mp3": require("@/assets/audio/challenges/i4-p1-q2.mp3"),
  "https://assets.linguaquest.app/audio/i4-p2-q1.mp3": require("@/assets/audio/challenges/i4-p2-q1.mp3"),
  "https://assets.linguaquest.app/audio/i4-p2-q2.mp3": require("@/assets/audio/challenges/i4-p2-q2.mp3"),
  "https://assets.linguaquest.app/audio/i4-p3-q1.mp3": require("@/assets/audio/challenges/i4-p3-q1.mp3"),
  "https://assets.linguaquest.app/audio/i4-p3-q2.mp3": require("@/assets/audio/challenges/i4-p3-q2.mp3"),
  "https://assets.linguaquest.app/audio/i4-p4-q1.mp3": require("@/assets/audio/challenges/i4-p4-q1.mp3"),
  "https://assets.linguaquest.app/audio/i4-p4-q2.mp3": require("@/assets/audio/challenges/i4-p4-q2.mp3"),
  "https://assets.linguaquest.app/audio/i4-p5-q1.mp3": require("@/assets/audio/challenges/i4-p5-q1.mp3"),
  "https://assets.linguaquest.app/audio/i4-p5-q2.mp3": require("@/assets/audio/challenges/i4-p5-q2.mp3"),
  "https://assets.linguaquest.app/audio/i5-p1-q1.mp3": require("@/assets/audio/challenges/i5-p1-q1.mp3"),
  "https://assets.linguaquest.app/audio/i5-p1-q2.mp3": require("@/assets/audio/challenges/i5-p1-q2.mp3"),
  "https://assets.linguaquest.app/audio/i5-p2-q1.mp3": require("@/assets/audio/challenges/i5-p2-q1.mp3"),
  "https://assets.linguaquest.app/audio/i5-p2-q2.mp3": require("@/assets/audio/challenges/i5-p2-q2.mp3"),
  "https://assets.linguaquest.app/audio/i5-p3-q1.mp3": require("@/assets/audio/challenges/i5-p3-q1.mp3"),
  "https://assets.linguaquest.app/audio/i5-p3-q2.mp3": require("@/assets/audio/challenges/i5-p3-q2.mp3"),
  "https://assets.linguaquest.app/audio/i5-p4-q1.mp3": require("@/assets/audio/challenges/i5-p4-q1.mp3"),
  "https://assets.linguaquest.app/audio/i5-p4-q2.mp3": require("@/assets/audio/challenges/i5-p4-q2.mp3"),
  "https://assets.linguaquest.app/audio/i5-p5-q1.mp3": require("@/assets/audio/challenges/i5-p5-q1.mp3"),
  "https://assets.linguaquest.app/audio/i5-p5-q2.mp3": require("@/assets/audio/challenges/i5-p5-q2.mp3"),
  "https://assets.linguaquest.app/audio/i6-p1-q1.mp3": require("@/assets/audio/challenges/i6-p1-q1.mp3"),
  "https://assets.linguaquest.app/audio/i6-p1-q2.mp3": require("@/assets/audio/challenges/i6-p1-q2.mp3"),
  "https://assets.linguaquest.app/audio/i6-p2-q1.mp3": require("@/assets/audio/challenges/i6-p2-q1.mp3"),
  "https://assets.linguaquest.app/audio/i6-p2-q2.mp3": require("@/assets/audio/challenges/i6-p2-q2.mp3"),
  "https://assets.linguaquest.app/audio/i6-p3-q1.mp3": require("@/assets/audio/challenges/i6-p3-q1.mp3"),
  "https://assets.linguaquest.app/audio/i6-p3-q2.mp3": require("@/assets/audio/challenges/i6-p3-q2.mp3"),
  "https://assets.linguaquest.app/audio/i6-p4-q1.mp3": require("@/assets/audio/challenges/i6-p4-q1.mp3"),
  "https://assets.linguaquest.app/audio/i6-p4-q2.mp3": require("@/assets/audio/challenges/i6-p4-q2.mp3"),
  "https://assets.linguaquest.app/audio/i6-p5-q1.mp3": require("@/assets/audio/challenges/i6-p5-q1.mp3"),
  "https://assets.linguaquest.app/audio/i6-p5-q2.mp3": require("@/assets/audio/challenges/i6-p5-q2.mp3"),
  "https://assets.linguaquest.app/audio/i7-p1-q1.mp3": require("@/assets/audio/challenges/i7-p1-q1.mp3"),
  "https://assets.linguaquest.app/audio/i7-p1-q2.mp3": require("@/assets/audio/challenges/i7-p1-q2.mp3"),
  "https://assets.linguaquest.app/audio/i7-p2-q1.mp3": require("@/assets/audio/challenges/i7-p2-q1.mp3"),
  "https://assets.linguaquest.app/audio/i7-p2-q2.mp3": require("@/assets/audio/challenges/i7-p2-q2.mp3"),
  "https://assets.linguaquest.app/audio/i7-p3-q1.mp3": require("@/assets/audio/challenges/i7-p3-q1.mp3"),
  "https://assets.linguaquest.app/audio/i7-p3-q2.mp3": require("@/assets/audio/challenges/i7-p3-q2.mp3"),
  "https://assets.linguaquest.app/audio/i7-p4-q1.mp3": require("@/assets/audio/challenges/i7-p4-q1.mp3"),
  "https://assets.linguaquest.app/audio/i7-p4-q2.mp3": require("@/assets/audio/challenges/i7-p4-q2.mp3"),
  "https://assets.linguaquest.app/audio/i7-p5-q1.mp3": require("@/assets/audio/challenges/i7-p5-q1.mp3"),
  "https://assets.linguaquest.app/audio/i7-p5-q2.mp3": require("@/assets/audio/challenges/i7-p5-q2.mp3"),
};

// Background music: remote URL -> bundled asset
const MUSIC_AUDIO: Record<string, number> = {
  "https://assets.mixkit.co/music/188/188.mp3": require("@/assets/audio/music/island-1.mp3"),
  "https://assets.mixkit.co/music/167/167.mp3": require("@/assets/audio/music/island-2.mp3"),
  "https://assets.mixkit.co/music/612/612.mp3": require("@/assets/audio/music/island-3.mp3"),
  "https://assets.mixkit.co/music/614/614.mp3": require("@/assets/audio/music/island-4.mp3"),
  "https://assets.mixkit.co/music/615/615.mp3": require("@/assets/audio/music/island-5.mp3"),
  "https://assets.mixkit.co/music/795/795.mp3": require("@/assets/audio/music/island-6.mp3"),
  "https://assets.mixkit.co/music/80/80.mp3": require("@/assets/audio/music/island-7.mp3"),
  "https://assets.mixkit.co/music/184/184.mp3": require("@/assets/audio/music/map.mp3"),
  "https://assets.mixkit.co/music/584/584.mp3": require("@/assets/audio/music/quest-ambient.mp3"),
};

/**
 * Resolve a remote audio URL to a bundled asset ID or pass-through.
 * Returns a number (require asset ID) for bundled files,
 * or { uri: string } for non-bundled URLs (online-only fallback).
 */
export function resolveAudioSource(remoteUrl: string): number | { uri: string } {
  const local = CHALLENGE_AUDIO[remoteUrl] ?? MUSIC_AUDIO[remoteUrl];
  if (local !== undefined) return local;
  return { uri: remoteUrl };
}
